### ISSUE TITLE
Docs are misleading for DSVM

### ISSUE THREAD

**Issue by Smarker** [Azure/pixel_level_land_classification#8]
> This tutorial requires the following programs:
> 
> Azure CLI 2.0
> AzCopy
> These programs are available for Windows and Linux. If you prefer not to install these programs locally, you may instead provision an Azure Data Science Virtual Machine

I provisioned a linux flavored DSVM, but when I ran `azcopy`, the command was not found. I don't believe that this comes preinstalled on the DSVM as the guide states. `az` is preinstalled.

**Comment by mawah** [comment]
Thanks for pointing this out, @Smarker! I've just updated the text to clarify for now, and have also asked the DSVM team to consider including azcopy in the Ubuntu image in their next release.
