### ISSUE TITLE
sku Property Mentioned Twice

### ISSUE THREAD

**Issue by Smarker** [Azure/pixel_level_land_classification#9]
In `create an azure account and populate with files` section of the readme `sku` property was mentioned twice:

> az storage account create --name %STORAGE_ACCOUNT_NAME% --sku Standard_LRS --sku Standard_LRS --resource-group %AZURE_RESOURCE_GROUP% --location eastus

**Comment by mawah** [comment]
Great catch -- thank you, @Smarker! I've just removed the second mention of the sku property.
